export const SET_LETTERS = 'SET_LETTERS';
export const IS_LOADING = 'IS_LOADING';
export const HAS_ERROR = 'HAS_ERROR';
export const VALIDATION_ERROR = 'VALIDATION_ERROR';
export const REMOVE_LETTERS = 'REMOVE_LETTERS';
export const SET_FORM_VALUE = 'SET_FORM_VALUE';
export const CANCEL_FETCHING = 'CANCEL_FETCHING';
export const INCREMENT_PAGE = 'INCREMENT_PAGE';
export const RESET_PAGE = 'RESET_PAGE';
export const UPDATE_LETTERS = 'UPDATE_LETTERS';


